title:        {"Rants"}
url:          http://rants.kinlane.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

production_url : http://rants.kinlane.com

BASE_PATH : http://rants.kinlane.com

categories_path : /categories.html
tags_path : /tags.html
